---
- name: Deploy Web Server
  hosts: web
  become: yes

  tasks:
    - name: Install Apache on Web Server
      yum:
        name: httpd
        state: present

    - name: Start Apache Service
      service:
        name: httpd
        state: started
        enabled: yes 
...