---
- name: Deploy Apache Web Server
  hosts: web
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and Enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy Default HTML Page
      copy:
        src: static.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'
