---
- name: Configure Server Security
  hosts: all
  become: yes


  tasks:
    - name: Ensure Firewall is Installed
      yum:
        name: firewalld
        state: present


    - name: Start Firewall
      service:
        name: firewalld
        state: started
        enabled: yes


    - name: Allow HTTP Traffic
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes


    - name: Allow SSH Traffic
      firewalld:
        service: ssh
        permanent: yes
        state: enabled
        immediate: yes
...