---
- name: Perform System Maintenance
  hosts: all
  become: yes

  tasks:
    - name: Update System Packages
      yum:
        name: '*'
        state: latest

    - name: Remove Unused Packages
      yum:
        autoremove: yes

    - name: Clean Package Cache
      command: yum clean all
