---
- name: Example of Variable Handling
  hosts: web
  become: yes


  vars:
    package_name: httpd
    service_name: httpd
    document_root: /var/www/html


  tasks:
    - name: Install Web Server
      yum:
        name: "{{ package_name }}"
        state: present


    - name: Start and Enable Web Service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes


    - name: Deploy Custom HTML Page
      copy:
        content: "<h1>Welcome to {{ ansible_hostname }}</h1>"
        dest: "{{ document_root }}/index.html"
...